version: "3"

networks:
  desafio:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_desafio
    ports:
      - "7001:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - desafio

  mysql:
    image: mysql:5.7.29
    container_name: mysql_desafio
    restart: unless-stopped
    tty: true
    ports:
      - "7002:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db_desafio
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql_desafio
    networks:
      - desafio

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php_desafio
    volumes:
      - ./src:/var/www/html
    ports:
      - "7003:9000"
    networks:
      - desafio
